Q1. Understanding Feature Distributions (Iris Dataset)

Context: Before training any ML model, we analyze feature distributions.

Dataset: Load Iris dataset from sklearn

Tasks:

1. Extract feature matrix as NumPy array
2. Compute:
Mean
Median
Standard deviation
Variance (for each feature)
3. Identify:
Which feature has highest variability and why it matters in ML
4. Convert any one feature into shape (n,1) and explain why ML models expect this format

In [1]:
import numpy as np
import pandas as pd
import sklearn1

In [24]:
#Task-1
iris = sklearn.datasets.load_iris()
features = iris.data
print(iris.feature_names)
print(features)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [6.7 3.  5.  1.7]
 [6.  2.9 4.5 1.5]
 [5.7 2.6 3.5 1. ]
 [5.5 2.4 3.8 1.1]
 [5.5 2.4 3.7 1. ]
 [5.8 2.7 3.9 1.2]
 [6.  2.7 5.1 1.6]
 [5.4 3.  4.5 1.5]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [6.3 2.3 4.4 1.3]
 [5.6 3.  4.1 1.3]
 [5.5 2.5 4.  1.3]
 [5.5 2.6 4.4 1.2]
 [6.1 3.  4.6 1.4]
 [5.8 2.6 4.  1.2]
 [5.  2.3 3.3 1. ]
 [5.6 2.7 4.2 1.3]
 [5.7 3.  4.2 1.2]
 [5.7 2.9 4.2 1.3]
 [6.2 2.9 4.3 1.3]
 [5.1 2.5 3.  1.1]
 [5.7 2.8 4.1 1.3]
 [6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]
 [7.6 3.  6.6 2.1]
 [4.9 2.5 4.5 1.7]
 [7.3 2.9 6.3 1.8]
 [6.7 2.5 5.8 1.8]
 [7.2 3.6 6.1 2.5]
 [6.5 3.2 5.1 2. ]
 [6.4 2.7 5.3 1.9]
 [6.8 3.  5.5 2.1]
 [5.7 2.5 5.  2. ]
 [5.8 2.8 5.1 2.4]
 [6.4 3.2 5.3 2.3]
 [6.5 3.  5.5 1.8]
 [7.7 3.8 6.7 2.2]
 [7.7 2.6 6.9 2.3]
 [6.  2.2 5.  1.5]
 [6.9 3.2 5.7 2.3]
 [5.6 2.8 4.9 2. ]
 [7.7 2.8 6.7 2. ]
 [6.3 2.7 4.9 1.8]
 [6.7 3.3 5.7 2.1]
 [7.2 3.2 6.  1.8]
 [6.2 2.8 4.8 1.8]
 [6.1 3.  4.9 1.8]
 [6.4 2.8 5.6 2.1]
 [7.2 3.  5.8 1.6]
 [7.4 2.8 6.1 1.9]
 [7.9 3.8 6.4 2. ]
 [6.4 2.8 5.6 2.2]
 [6.3 2.8 5.1 1.5]
 [6.1 2.6 5.6 1.4]
 [7.7 3.  6.1 2.3]
 [6.3 3.4 5.6 2.4]
 [6.4 3.1 5.5 1.8]
 [6.  3.  4.8 1.8]
 [6.9 3.1 5.4 2.1]
 [6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [5.8 2.7 5.1 1.9]
 [6.8 3.2 5.9 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]

In [20]:
#Task-2
features_mean = np.mean(features, axis = 0)
features_median = np.median(features, axis = 0)
features_std = np.std(features, axis = 0)
features_variance = np.var(features, axis = 0)
print("Mean :" ,features_mean)
print("Median :" ,features_median)
print("Std :" ,features_std)
print("Variance :" ,features_variance)

Mean : [5.84333333 3.05733333 3.758      1.19933333]
Median : [5.8  3.   4.35 1.3 ]
Std : [0.82530129 0.43441097 1.75940407 0.75969263]
Variance : [0.68112222 0.18871289 3.09550267 0.57713289]

In [27]:
#Task-3
highest_variability = np.max(features_std)
index_of_variability = np.argmax(features_std)
print("Highest variablity in features is of the one which has the highest standard deviation, which is :")
print(f"Feature name: {iris.feature_names[index_of_variability]}  Feature deviation: {highest_variability}")

Highest variablity in features is of the one which has the highest standard deviation, which is :
Feature name: petal length (cm)  Feature deviation: 1.7594040657753032

In [30]:
features.shape

(150, 4)

In [64]:
#Task-4
feature_new_shape = iris.data[:,0].reshape(-1,1)

Q2. Data Selection for Model Input

Context: Models are trained on selective features, not full raw data.

Dataset: Iris

Tasks:

1. Extract:
First 100 samples
Only last 2 features
2. Use boolean masking:
Select samples where petal length is greater than dataset mean
3. Count selected samples
4. Explain how this relates to feature-based filtering in ML

In [42]:
import pandas as pd
import numpy as np
from sklearn import datasets

In [48]:
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [58]:
#Task-1
samples = df.iloc[:100, -2:]
samples

    petal length (cm)  petal width (cm)
0                 1.4               0.2
1                 1.4               0.2
2                 1.3               0.2
3                 1.5               0.2
4                 1.4               0.2
..                ...               ...
95                4.2               1.2
96                4.2               1.3
97                4.3               1.3
98                3.0               1.1
99                4.1               1.3

[100 rows x 2 columns]

In [57]:
#Task-2
samples[samples["petal length (cm)"] > samples["petal length (cm)"].mean()].head()

    petal length (cm)  petal width (cm)
50                4.7               1.4
51                4.5               1.5
52                4.9               1.5
53                4.0               1.3
54                4.6               1.5

In [60]:
#Task-3
samples[samples["petal length (cm)"] > samples["petal length (cm)"].mean()].shape[0]

50

Q3. Feature Scaling using NumPy (Very Important)

Context: Most ML models require normalized data.

Dataset: Iris (NumPy array)

Tasks:

1. Apply standardization:

$$
X' = \frac{X - \mu}{\sigma}
$$
	​2. 

Verify:
Mean ≈ 0
Std ≈
on

In [65]:
feature_data = iris.data

In [76]:
#Task-1
feature_mean = np.mean(feature_data, axis=0)
feature_std = np.std(feature_data, axis=0)
standardized_feature_data = (feature_data - feature_mean)/feature_std

In [68]:
#Task-2
print("Mean after standardization:", np.mean(standardized_feature_data, axis=0))
print("Std after standardization:", np.std(standardized_feature_data, axis=0))

Mean after standardization: [-1.69031455e-15 -1.84297022e-15 -1.69864123e-15 -1.40924309e-15]
Std after standardization: [1. 1. 1. 1.]

Q4. Dataset Understanding (Titanic Dataset)

Context: First step in ML pipeline is dataset inspection.

Dataset: Titanic (Seaborn)

Tasks:

1. Display:
head(), tail()
info(), describe()
2. Identify:
Missing values per column
Numerical vs categorical features
3. Explain:
Why identifying feature types is important before modeling

In [131]:
import seaborn as sns
df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [132]:
df.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [133]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [134]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [135]:
#Task-2
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [136]:
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns
categorical_cols = df.select_dtypes(include=['object', 'category', 'bool']).columns
numerical_cols

Index(['survived', 'pclass', 'age', 'sibsp', 'parch', 'fare'], dtype='object')

Q5. Filtering Data for Business Logic

Context: Real ML problems require filtering relevant populations.

Dataset: Titanic

Tasks:

1. Filter:
Female passengers in 1st class
2. Compute:
Survival rate for this group
3. Compare with overall survival rate
4. Interpret:
What insight can be used in ML feature engineering

In [137]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [138]:
#Task-1
female_survived = df[(df["sex"] == "female") & (df["class"] == "First")]
female_survived.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
31,1,1,female,NaN,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
52,1,1,female,49.0,1,0,76.7292,C,First,woman,False,D,Cherbourg,yes,False

In [139]:
#Task-2
(female_survived[female_survived["survived"] == 1]).shape[0] / female_survived.shape[0] * 100

96.80851063829788

In [140]:
#task-3
print(f"Overall Survivability: {(df[df["survived"] == 1]).shape[0] / df.shape[0] * 100}")
print(f"Women Survivability in First Class: {(female_survived[female_survived["survived"] == 1]).shape[0] / female_survived.shape[0] * 100}")

Overall Survivability: 38.38383838383838
Women Survivability in First Class: 96.80851063829788

Q6. Handling Missing Data (Critical ML Step)

Context: Models cannot handle null values.

Dataset: Titanic

Tasks:

1. Fill missing age using median
2. Fill missing embarked using mode
3. Drop deck column
4. Explain:
Why different strategies are used for different columns

In [141]:
df["age"].isna().sum()

np.int64(177)

In [142]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [143]:
#Task-1
df["age"] = df["age"].fillna(df["age"].median())

In [144]:
df["age"].isna().sum()

np.int64(0)

In [145]:
df["embarked"].isna().sum()

np.int64(2)

In [146]:
#task-2
df["embarked"] = df["embarked"].fillna(df["embarked"].mode()[0])

In [147]:
df["embarked"].isna().sum()

np.int64(0)

In [148]:
#Task-3
df.drop(columns= "deck",axis = 0, inplace=True)

In [149]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

Q7. Feature Engineering for Model Improvement

Context: Raw data is rarely useful—features must be created.

Dataset: Titanic

Tasks:

1. Create:
family_size = sibsp + parch + 1
2. Create:
is_alone (binary feature)
3. Compute survival rate by is_alone
4. Explain:
Why engineered features improve ML models

In [172]:
df_new = sns.load_dataset("titanic")
df_new.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [173]:
#Task-1
df_new["family_size"] = df_new["sibsp"] + df_new["parch"] + 1
df_new.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family_size
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,2
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,2
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,1
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,2
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,1

In [174]:
df_new.family_size.unique()

array([ 2,  1,  5,  3,  7,  6,  4,  8, 11])

In [175]:
#Task-2
df_new["is_alone"] = df_new["alone"].map({False : 0, True : 1})
df_new.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family_size,is_alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,2,0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,2,0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,1,1
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,2,0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,1,1

In [180]:
#Task-3
survived_by_is_alone= df_new.groupby("is_alone")["survived"].mean()
survived_by_is_alone*100

is_alone
0    50.564972
1    30.353818
Name: survived, dtype: float64

Q8. Group-Based Insights (Customer Segmentation Logic)

Context: ML models often depend on aggregated patterns.

Dataset: Tips

Tasks:

1. Compute:
Average tip by day
Total bill by gender
2. Create new feature:
tip_percentage
3. Identify:
Which day has highest tipping behavior
4. Explain:
How this helps in segmentation models

In [181]:
df_tips = sns.load_dataset("tips")
df_tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [184]:
#Task-1
avg_tip = df_tips.groupby("day", observed=True)["tip"].mean()
avg_tip

day
Thur    2.771452
Fri     2.734737
Sat     2.993103
Sun     3.255132
Name: tip, dtype: float64

In [185]:
total_bill = df_tips.groupby("day", observed=True)["total_bill"].sum()
total_bill

day
Thur    1096.33
Fri      325.88
Sat     1778.40
Sun     1627.16
Name: total_bill, dtype: float64

In [186]:
#Task-2
df_tips["tip_percentage"] = df_tips["tip"] / df_tips["total_bill"] * 100
df_tips.head()

   total_bill   tip     sex smoker  day    time  size  tip_percentage
0       16.99  1.01  Female     No  Sun  Dinner     2        5.944673
1       10.34  1.66    Male     No  Sun  Dinner     3       16.054159
2       21.01  3.50    Male     No  Sun  Dinner     3       16.658734
3       23.68  3.31    Male     No  Sun  Dinner     2       13.978041
4       24.59  3.61  Female     No  Sun  Dinner     4       14.680765

In [193]:
#Task-3
highest_tip_day = df_tips.groupby("day", observed=True)["tip"].sum().idxmax()
highest_tip_day

'Sat'

Q9. Advanced Filtering + Subsetting

Context: Training data is often filtered based on business rules.

Dataset: Tips

Tasks:

1. Filter:
total_bill > 20 AND tip < 3
2. Select only relevant columns
3. Analyze:
Is this segment under-tipping?
4. Explain:
How such filtering helps anomaly detection

In [194]:
df_tips.head()

   total_bill   tip     sex smoker  day    time  size  tip_percentage
0       16.99  1.01  Female     No  Sun  Dinner     2        5.944673
1       10.34  1.66    Male     No  Sun  Dinner     3       16.054159
2       21.01  3.50    Male     No  Sun  Dinner     3       16.658734
3       23.68  3.31    Male     No  Sun  Dinner     2       13.978041
4       24.59  3.61  Female     No  Sun  Dinner     4       14.680765

In [195]:
#Task-1
filtered_data = df_tips[(df_tips["total_bill"] > 20) & (df_tips["tip"] < 3)]
filtered_data.head()

    total_bill   tip     sex smoker  day    time  size  tip_percentage
21       20.29  2.75  Female     No  Sat  Dinner     2       13.553475
33       20.69  2.45  Female     No  Sat  Dinner     4       11.841469
48       28.55  2.05    Male     No  Sun  Dinner     3        7.180385
57       26.41  1.50  Female     No  Sat  Dinner     2        5.679667
68       20.23  2.01    Male     No  Sat  Dinner     2        9.935739

In [201]:
filtered_data_sex = filtered_data[["sex","total_bill","tip","tip_percentage"]]
filtered_data_sex.head()

       sex  total_bill   tip  tip_percentage
21  Female       20.29  2.75       13.553475
33  Female       20.69  2.45       11.841469
48    Male       28.55  2.05        7.180385
57  Female       26.41  1.50        5.679667
68    Male       20.23  2.01        9.935739

In [202]:
grouped_by_sex = filtered_data_sex.groupby("sex", observed=True)["tip_percentage"].mean()
grouped_by_sex

sex
Male       8.273373
Female    10.397995
Name: tip_percentage, dtype: float64

Q10. Data Transformation for Model Input (NumPy)

Context: ML models require structured numeric arrays.

Tasks:

1. Create two arrays of shape (3,2)
2. Perform:
Vertical stacking
Horizontal stacking
3. Reshape into (2,6)
4. Explain:
Why reshaping is required in ML pipelines

In [206]:
#Task-1
x = np.random.randint(0,10,size=(3,2))
y = np.random.randint(0,10,size=(3,2))
x,y

(array([[0, 4],
        [2, 2],
        [0, 1]], dtype=int32),
 array([[2, 9],
        [3, 0],
        [7, 7]], dtype=int32))

In [208]:
#Task-2,3
xy_vertical_stack = np.vstack([x,y]).reshape(2,6)
xy_vertical_stack

array([[0, 4, 2, 2, 0, 1],
       [2, 9, 3, 0, 7, 7]], dtype=int32)

Q11. End-to-End ML Preprocessing Pipeline (Titanic)

Context: Prepare dataset for ML model training

Tasks:

1. Load dataset
2. Handle missing values
3. Encode categorical variables (sex, embarked)
4. Normalize numerical features
5. Convert to NumPy array

Output:

Final feature matrix ready for model training

In [225]:
#Task-1
df_titanic = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [226]:
df_titanic.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [227]:
#Task-2
df_titanic["age"] = df_titanic["age"].fillna(df_titanic["age"].median())
df_titanic["embarked"] = df_titanic["embarked"].fillna(df_titanic["embarked"].mode()[0])
df_titanic["embark_town"] = df_titanic["embark_town"].fillna(df_titanic["embark_town"].mode()[0])
df_titanic.drop(columns= "deck", inplace=True)

In [228]:
df_titanic.isna().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [229]:
df_titanic["embarked"].unique()

array(['S', 'C', 'Q'], dtype=object)

In [230]:
#Task-3
df_titanic["sex"] = df_titanic["sex"].map({"male" : 0, "female" : 1})
df_titanic["class"] = df_titanic["class"].map({"Third" : 0, "Second" : 1, "First": 2})
df_titanic = pd.get_dummies(df_titanic, columns= ["embarked", "embark_town"], drop_first=True, dtype=int)
df_titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,class,who,adult_male,alive,alone,embarked_Q,embarked_S,embark_town_Queenstown,embark_town_Southampton
0,0,3,0,22.0,1,0,7.2500,0,man,True,no,False,0,1,0,1
1,1,1,1,38.0,1,0,71.2833,2,woman,False,yes,False,0,0,0,0
2,1,3,1,26.0,0,0,7.9250,0,woman,False,yes,True,0,1,0,1
3,1,1,1,35.0,1,0,53.1000,2,woman,False,yes,False,0,1,0,1
4,0,3,0,35.0,0,0,8.0500,0,man,True,no,True,0,1,0,1

In [234]:
#Task-4
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df_titanic_scaled = scaler.fit_transform(df_titanic[["age","fare"]])
df_titanic[["age","fare"]] = df_titanic_scaled #converting back to dataframe for overview as previous action would result in a numpy array
df_titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,class,who,adult_male,alive,alone,embarked_Q,embarked_S,embark_town_Queenstown,embark_town_Southampton
0,0,3,0,-0.565736,1,0,-0.502445,0,man,True,no,False,0,1,0,1
1,1,1,1,0.663861,1,0,0.786845,2,woman,False,yes,False,0,0,0,0
2,1,3,1,-0.258337,0,0,-0.488854,0,woman,False,yes,True,0,1,0,1
3,1,1,1,0.433312,1,0,0.420730,2,woman,False,yes,False,0,1,0,1
4,0,3,0,0.433312,0,0,-0.486337,0,man,True,no,True,0,1,0,1

Q12. Feature Selection using Statistical Understanding

Context: Not all features improve model performance.

Dataset: Iris

Tasks:

1. Compute correlation matrix
2. Identify highly correlated features
3. Drop redundant features
4. Explain:
Impact on overfitting and model performance

In [235]:
df_iris = sns.load_dataset("iris")
df_iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [237]:
#Task-1
corr_matrx = df_iris.corr(numeric_only=True)
corr_matrx

              sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.117570      0.871754     0.817941
sepal_width      -0.117570     1.000000     -0.428440    -0.366126
petal_length      0.871754    -0.428440      1.000000     0.962865
petal_width       0.817941    -0.366126      0.962865     1.000000

In [238]:
#Task-2
df_iris.drop(columns="petal_length", inplace=True) #Dropped due to high correlation with other features
df_iris.head()

   sepal_length  sepal_width  petal_width species
0           5.1          3.5          0.2  setosa
1           4.9          3.0          0.2  setosa
2           4.7          3.2          0.2  setosa
3           4.6          3.1          0.2  setosa
4           5.0          3.6          0.2  setosa

Q13. Custom Feature Transformation using apply()

Context: Real ML requires custom logic transformation.

Dataset: Titanic

Tasks:

1. Create age_group:
Child / Adult / Senior
2. Use .apply()
3. Compute survival rate per group
4. Interpret:
Which segment has highest survival likelihood

In [243]:
data = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [244]:
#Task-1
data["age_group"] = data["age"].apply(lambda age: "Child" if age < 18 else "Adult" if age <= 60 else "Senior")
data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age_group
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,Adult
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,Adult
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,Adult
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,Adult
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,Adult

In [245]:
#task-3
data.groupby("age_group")["survived"].mean()

age_group
Adult     0.386874
Child     0.539823
Senior    0.286432
Name: survived, dtype: float64

In [246]:
data.groupby("age_group")["survived"].mean().reset_index(name="survival_rate")

  age_group  survival_rate
0     Adult       0.386874
1     Child       0.539823
2    Senior       0.286432

Q14. Error Analysis Simulation (Model Evaluation Thinking)

Context: Understanding prediction errors is key in ML.

Tasks:

1. Generate 1000 random error values using NumPy
2. Compute:
Mean
Standard deviation
3. Identify outliers:
Using mean ± 2*std
4. Explain:
What high variance means in model performance

In [259]:
#Task-1,2,3
np.random.seed(10)
a = np.random.randn(1000)
std_a = np.std(a)
mean_a = np.mean(a)
lower = mean_a - 2*std_a
upper = mean_a + 2*std_a
outliers = a[(a < lower) | (a > upper)]
print(outliers) 
print(len(outliers))

[-1.97772828  2.38496733  2.39470366  2.46765106  1.98508459 -2.13171211
 -1.99439377 -1.95451212 -1.90745689  2.40432561  2.46532508  1.98538575
 -2.97959677 -2.29510333  2.22504964 -1.94129968 -2.01771865  1.90230404
  2.31912732 -2.39557201  2.67991031  1.86295167 -1.9836365   2.20096644
 -2.17660863 -3.20440134  2.38412462 -2.09779187  2.2418665   2.67168509
  2.07504867 -2.81600122  2.66257747  2.06562572 -1.98710415  1.86998782
 -1.90101374  2.2048857  -1.8916454  -1.96251852  2.10803801  2.15197051
  1.99000551 -2.5114691   2.19559674 -2.81506131  2.11859144 -1.9219949
 -2.21075441 -2.00797519 -1.91688659  1.91565259 -2.43420867  2.11109854
 -1.89459389]
55

Q15. Business + ML Insight Problem (Tips Dataset)

Context: Convert data analysis into decision-making

Tasks:

1. Create:
tip_percentage
2. Group by:
day and time
3. Identify:
Highest revenue segment
4. Provide:
Recommendation for business strategy
How ML model can use this insight

In [260]:
data_tip = sns.load_dataset("tips")
data_tip.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [262]:
#Task-1
data_tip["tip_percentage"] = data_tip["tip"] / data_tip["total_bill"]
data_tip.head()

   total_bill   tip     sex smoker  day    time  size  tip_percentage
0       16.99  1.01  Female     No  Sun  Dinner     2        0.059447
1       10.34  1.66    Male     No  Sun  Dinner     3        0.160542
2       21.01  3.50    Male     No  Sun  Dinner     3        0.166587
3       23.68  3.31    Male     No  Sun  Dinner     2        0.139780
4       24.59  3.61  Female     No  Sun  Dinner     4        0.146808

In [268]:
#task-2
tip_per_time_and_day = data_tip.groupby(["day","time"], observed = True)["tip_percentage"].mean()
tip_per_time_and_day

day   time
Thur  Lunch     0.161301
      Dinner    0.159744
Fri   Lunch     0.188765
      Dinner    0.158916
Sat   Dinner    0.153152
Sun   Dinner    0.166897
Name: tip_percentage, dtype: float64

In [274]:
#Task-3
revenue_segment_sex = data_tip.groupby(["sex","day","time"], observed=True)["total_bill"].mean()
print(f"Highest revenue segment is: {revenue_segment_sex.idxmax()}, with total earnings of {revenue_segment_sex.max()}")

Highest revenue segment is: ('Male', 'Fri', 'Dinner'), with total earnings of 23.487142857142857